name: Deploy to GitHub Pages & Run Crawler

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']
    
  # Runs on schedule for crawler
  schedule:
    # Täglich um 3 Uhr nachts (UTC)
    - cron: '0 3 * * *'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build PWA
        run: npm run build
        env:
          # Wichtig für GitHub Pages - setzt den korrekten base path
          BASE_URL: /olieder.github.io/dbb-mini-bball-coach-app/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Crawler job - läuft nach Deploy
  crawl-clubs:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run Club Crawler
        run: |
          echo "🕷️ Starting club crawler..."
          npm run crawl:clubs:all
        continue-on-error: true
        
      - name: Update Club Data
        run: |
          echo "📊 Processing crawled data..."
          npm run split:clubs
        continue-on-error: true
        
      - name: Commit Updated Data
        if: github.event_name == 'schedule'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update club data [skip ci]"
          
      - name: Push changes
        if: github.event_name == 'schedule'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  # Optional: Lighthouse CI for PWA performance
  lighthouse:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4
      
      - name: Lighthouse CI Action
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
          uploadArtifacts: true
          temporaryPublicStorage: true
