name: Deploy to GitHub Pages & Run Crawler

on:
  push:
    branches: ['main']
    paths:
      - 'basketball-app/**'
      
  schedule:
    # Täglich um 3 Uhr nachts (UTC)
    - cron: '0 3 * * *'
    
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'basketball-app/package-lock.json'
          
      - name: Install dependencies
        working-directory: basketball-app
        run: npm ci
        
      - name: Build PWA
        working-directory: basketball-app
        run: npm run build
        env:
          BASE_URL: /dbb-mini-bball-coach-app/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./basketball-app/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  crawl-clubs:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'basketball-app/package-lock.json'
          
      - name: Install dependencies
        working-directory: basketball-app
        run: npm ci
        
      - name: Run Club Crawler
        working-directory: basketball-app
        run: |
          echo "🕷️ Starting club crawler..."
          npm run crawl:clubs:all
        continue-on-error: true
        
      - name: Commit Updated Data
        if: github.event_name == 'schedule'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update club data [skip ci]"
          
      - name: Push changes
        if: github.event_name == 'schedule'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
